name: Trigger by tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: The job has succeeded
        if: startsWith(github.event.ref, 'refs/tags')
      - name: tag version
        run: |
            echo DEPLOY ON VERSION :  $GITHUB_REF_NAME
 
