name: CI AND CD

on:
  push:
    branches:
      - demo
  pull_request:
    types: [opened, synchronize, reopened]

jobs:

  code-quality:
    runs-on: ubuntu-latest
    env:
      SONAR_EXCLUSIONS: '**/*.html,**/*.phtml,**/*.css,**/*.js'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
    
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          projectBaseDir: "src/"
        with:
          args: >
            -Dsonar.projectKey=${{ github.repository_owner }}_${{ github.event.repository.name }}_${{ github.ref_name }}
            -Dsonar.exclusions=${{ env.SONAR_EXCLUSIONS }}
    
  build-image:
    needs: code-quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build The Docker Image
        run: docker build . --file Dockerfile --tag my-app:$(date +%s)
  
  push-image:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      

     