name: Create Release Branch
on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 5.5.0)'
        required: true
      versionCode:
        description: 'Version number (50500)'
        required: true
jobs:
  createrelease:
    runs-on: ubuntu-latest

    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: samansupriadi
        repo: crm-ops
        github_token: ${{ vars.REPO_TOKEN }}
        comment_downstream_url: ${{ github.event.pull_request.comments_url }}
