name: Greeting on variable day

on:
    push:
      branches :  ["demo", "dev", "test"]
    # pull_request:
    #   branches: ["demo", "dev", "test"]
    #   types: ["closed"]

# env:
#     APP_ENV: ${{ github.ref_name == 'demo' && 'demo' || github.ref_name == 'dev' && 'development' || github.ref_name == 'staging-qa' && 'staging' || github.ref_name == 'main' && 'production'  }}

# jobs:
#   greeting_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Say Hello Mona it's Monday ${{ env.APP_ENV }} "
#         run: echo "lalalal $APP_ENV"

jobs:
  set_target_env:
    name: "Define which environment will use"
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.set_env.outputs.test }}
      output2: ${{ steps.set_version.outputs.test }}
    steps:
      - id: set_env
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: set_version
        run: echo "test=world" >> "$GITHUB_OUTPUT"
  job2:
    runs-on: ubuntu-latest
    needs: set_target_env
    steps:
      - env:
          OUTPUT1: ${{needs.set_target_env.outputs.output1}}
          OUTPUT2: ${{needs.set_target_env.outputs.output2}}
        run: echo "$OUTPUT1 $OUTPUT2"
