name: Greeting on variable day 2

on:
    push:
      branches :  ["demo", "dev", "test"]
    pull_request:
      branches: ["demo", "dev", "test", "development"]
      types: ["closed"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
        
      - name: Run entrypoint.sh
        run: |
         bash entrypoint.sh owner="samansupriadi" repo="crm-ops" github_token="${{ vars.REPO_TOKEN }}" workflow_file_name="blank.yaml"
