name: Greeting on variable day

on:
    push:
      branches :  ["demo", "dev", "test"]
    # pull_request:
    #   branches: ["demo", "dev", "test"]
    #   types: ["closed"]

# env:
#     APP_ENV: ${{ github.ref_name == 'demo' && 'demo' || github.ref_name == 'dev' && 'development' || github.ref_name == 'staging-qa' && 'staging' || github.ref_name == 'main' && 'production'  }}

# jobs:
#   greeting_job:
#     runs-on: ubuntu-latest
#     steps:
#       - name: "Say Hello Mona it's Monday ${{ env.APP_ENV }} "
#         run: echo "lalalal $APP_ENV"

jobs:
  get_target_env:
    name: 'Get target env'
    runs-on: ubuntu-latest
    outputs:
      target_env: ${{ steps.set_result.outputs.target_env }}
    steps:
      - name: 'Set env based on branch'
        id: set_results
        shell: bash
        run: |
          echo "Branch: ${{ github.ref_name }}"
          echo "target_env=${{ github.ref_name }}" >> $GITHUB_OUTPUT


  automated_job:
    name: 'My Automated Job'
    runs-on: ubuntu-latest
    needs: get_target_env
    environment:
      name: ${{ needs.get_target_env.outputs.target_env }}
    steps:
      - name: 'Print env name'
        env:
          target: ${{ needs.get_target_env.outputs.target_env }}
        run: echo "Using $target"