name: Greeting on variable day 2

on:
    push:
      branches :  ["demo", "dev", "test"]
    pull_request:
      branches: ["demo", "dev", "test", "development"]
      types: ["closed"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
    - uses: convictional/trigger-workflow-and-wait@v1.6.1
      with:
        owner: keithconvictional
        repo: myrepo
        github_token: ${{ secrets.GITHUB_PERSONAL_ACCESS_TOKEN }}
        comment_downstream_url: ${{ github.event.pull_request.comments_url }}
