name: Greeting on variable day

on:
    pull_request:
      branches: ["demo", "dev", "test"]
      types: ["closed"]

env:
    APP_ENV: ${{ github.ref_name == 'demo' && 'demodemo' || 'value_for_other_branches' }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello Mona it's Monday 1. ${{ github.ref_name }} 2.  ${GITHUB_REF##*/}"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! $APP_ENV"
        env:
          First_Name: Mona
