name: Greeting on variable day 2

on:
    push:
      branches :  ["demo", "dev", "test"]
    pull_request:
      branches: ["demo", "dev", "test", "development"]
      types: ["closed"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: lasith-kg/dispatch-workflow@v1
        id: repository-dispatch
        name: 'Dispatch Workflow using repository_dispatch Method'
        with:
          dispatch-method: repository_dispatch
          repo: crm-ops
          owner: samansupriadi
          event-type: deploy # Event To Trigger From Workflow
          token: ${{ vars.REPO_TOKEN }} # GitHub Token With Relevant Permissions
          workflow-inputs: |
            {
              "string-type": "placeholder",
              "nested": {                    // Supports Nesting
                "number-type": 1,            // Supports Native 'Number' types
                "boolean-type": true         // Supports Native 'Boolean' types
              }
            }
