name: Greeting on variable day

on:
    pull_request:
      branches: ["demo", "dev", "test"]
      types: ["closed"]

env:
    APP_ENV: ${{ github.ref_name == 'demo' && 'demo' || github.ref_name == 'dev' && 'development' || github.ref_name == 'staging-qa' && 'staging' || github.ref_name == 'main' && 'production'  }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday ${{ env.APP_ENV }} "
        run: echo "lalalal $APP_ENV"