name: Greeting on variable day

on:
    pull_request:
      branches: ["demo", "dev", "test"]
      types: ["closed"]

env:
    APP_ENV: ${{ github.ref_name == 'demo' && 'demodemo' || 'value_for_other_branches' }}

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    steps:
      - name: "Say Hello Mona it's Monday $APP_ENV "
        run: echo "lalalal $APP_ENV"