name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-passing-data:
    permissions:
      contents: read
      pull-requests: write
    uses: samansupriadi/crm/.github/workflows/workflow-B.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
