<?php

namespace Database\Seeders;

use App\Models\Program;
use App\Models\ProgramCategory;
use Illuminate\Database\Seeder;
use Symfony\Component\Uid\Ulid;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ProgramSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $datas = '
        [
            {"productid":"1234","productname":"CSR-CSR","productcategory":"CSR"},
            {"productid":"1235","productname":"Dana Kemanusiaan-Banjir Jakarta","productcategory":"Dana Kemanusiaan"},
            {"productid":"1236","productname":"Dana Kemanusiaan-Banjir Wasior Papua","productcategory":"Dana Kemanusiaan"},
            {"productid":"1237","productname":"Dana Kemanusiaan-Bencana Sulawesi","productcategory":"Dana Kemanusiaan"},
            {"productid":"1238","productname":"Dana Kemanusiaan-GAZA FOOD BANK","productcategory":"Dana Kemanusiaan"},
            {"productid":"1239","productname":"Dana Kemanusiaan-Gempa Aceh","productcategory":"Dana Kemanusiaan"},
            {"productid":"1240","productname":"Dana Kemanusiaan-Gempa Jogya","productcategory":"Dana Kemanusiaan"},
            {"productid":"1241","productname":"Dana Kemanusiaan-Gempa Lombok","productcategory":"Dana Kemanusiaan"},
            {"productid":"1242","productname":"Dana Kemanusiaan-Gempa Nepal","productcategory":"Dana Kemanusiaan"},
            {"productid":"1243","productname":"Dana Kemanusiaan-Gempa Sumatra","productcategory":"Dana Kemanusiaan"},
            {"productid":"1244","productname":"Dana Kemanusiaan-Gunung Meletus","productcategory":"Dana Kemanusiaan"},
            {"productid":"1245","productname":"Dana Kemanusiaan-Heart For Palestine","productcategory":"Dana Kemanusiaan"},
            {"productid":"1246","productname":"Dana Kemanusiaan-Help Bima","productcategory":"Dana Kemanusiaan"},
            {"productid":"1247","productname":"Dana Kemanusiaan-Humanity for Palestine","productcategory":"Dana Kemanusiaan"},
            {"productid":"1248","productname":"Dana Kemanusiaan-Kemanusiaan","productcategory":"Dana Kemanusiaan"},
            {"productid":"1249","productname":"Dana Kemanusiaan-Korban Kabut Asap","productcategory":"Dana Kemanusiaan"},
            {"productid":"1250","productname":"Dana Kemanusiaan-Letusan Merapi Jogja","productcategory":"Dana Kemanusiaan"},
            {"productid":"1251","productname":"Dana Kemanusiaan-Longsor Jawa Tengah","productcategory":"Dana Kemanusiaan"},
            {"productid":"1252","productname":"Dana Kemanusiaan-Longsor Pangalengan","productcategory":"Dana Kemanusiaan"},
            {"productid":"1253","productname":"Dana Kemanusiaan-Peduli Banjir Bandung Selatan","productcategory":"Dana Kemanusiaan"},
            {"productid":"1254","productname":"Dana Kemanusiaan-Peduli Gempa Jabar Selatan","productcategory":"Dana Kemanusiaan"},
            {"productid":"1255","productname":"Dana Kemanusiaan-Peduli Longsor Jabar","productcategory":"Dana Kemanusiaan"},
            {"productid":"1256","productname":"Dana Kemanusiaan-Pray For Egypt","productcategory":"Dana Kemanusiaan"},
            {"productid":"1257","productname":"Dana Kemanusiaan-Rohingnya Myanmar","productcategory":"Dana Kemanusiaan"},
            {"productid":"1258","productname":"Dana Kemanusiaan-Save Aleppo","productcategory":"Dana Kemanusiaan"},
            {"productid":"1259","productname":"Dana Kemanusiaan-Save Garut","productcategory":"Dana Kemanusiaan"},
            {"productid":"1260","productname":"Dana Kemanusiaan-Save Muslim Rohingya","productcategory":"Dana Kemanusiaan"},
            {"productid":"1261","productname":"Dana Kemanusiaan-Sinergi Peduli Bencana","productcategory":"Dana Kemanusiaan"},
            {"productid":"1262","productname":"Dana Kemanusiaan-Solidaritas Gempa Indonesia","productcategory":"Dana Kemanusiaan"},
            {"productid":"1263","productname":"Dana Kemanusiaan-Somalia","productcategory":"Dana Kemanusiaan"},
            {"productid":"1264","productname":"Dana Kemanusiaan-Tsunami Aceh","productcategory":"Dana Kemanusiaan"},
            {"productid":"1265","productname":"Dana Kemanusiaan-Tsunami Mentawai","productcategory":"Dana Kemanusiaan"},
            {"productid":"1266","productname":"Dana Kemanusiaan-Tunai","productcategory":"Dana Kemanusiaan"},
            {"productid":"1267","productname":"Entitas-infak","productcategory":"Entitas"},
            {"productid":"1268","productname":"Entitas-zakat","productcategory":"Entitas"},
            {"productid":"1269","productname":"Green Kurban-Gabung Sapi","productcategory":"Green Kurban"},
            {"productid":"1270","productname":"Green Kurban-Infak","productcategory":"Green Kurban"},
            {"productid":"1271","productname":"Green Kurban-Kambing A","productcategory":"Green Kurban"},
            {"productid":"1272","productname":"Green Kurban-Kambing B","productcategory":"Green Kurban"},
            {"productid":"1273","productname":"Green Kurban-Kambing C","productcategory":"Green Kurban"},
            {"productid":"1274","productname":"Green Kurban-Patungan","productcategory":"Green Kurban"},
            {"productid":"1275","productname":"Green Kurban-Sapi","productcategory":"Green Kurban"},
            {"productid":"1276","productname":"Green Kurban-Sapi Nasional","productcategory":"Green Kurban"},
            {"productid":"1277","productname":"Hasil Wakaf-Air Galon Taqua 99","productcategory":"Hasil Wakaf"},
            {"productid":"1278","productname":"Hasil Wakaf-Apotik","productcategory":"Hasil Wakaf"},
            {"productid":"1279","productname":"Hasil Wakaf-Barang Bekas Berkwalitas","productcategory":"Hasil Wakaf"},
            {"productid":"1280","productname":"Hasil Wakaf-Kebab Corner Ciganitri","productcategory":"Hasil Wakaf"},
            {"productid":"1281","productname":"Hasil Wakaf-Lain-lain","productcategory":"Hasil Wakaf"},
            {"productid":"1282","productname":"Hasil Wakaf-Ozil kebab","productcategory":"Hasil Wakaf"},
            {"productid":"1283","productname":"Hasil Wakaf-Pelayanan Mobil Jenazah","productcategory":"Hasil Wakaf"},
            {"productid":"1284","productname":"Hasil Wakaf-Pengelolaan Gedung Wakaf","productcategory":"Hasil Wakaf"},
            {"productid":"1285","productname":"Hasil Wakaf-Pengelolaan Wisma Ayu","productcategory":"Hasil Wakaf"},
            {"productid":"1286","productname":"Hasil Wakaf-PGS 1","productcategory":"Hasil Wakaf"},
            {"productid":"1287","productname":"Hasil Wakaf-PGS 2","productcategory":"Hasil Wakaf"},
            {"productid":"1288","productname":"Hasil Wakaf-RM Ampera Pasteur","productcategory":"Hasil Wakaf"},
            {"productid":"1289","productname":"Hasil Wakaf-Toko Vamosh","productcategory":"Hasil Wakaf"},
            {"productid":"1290","productname":"Hasil Wakaf-Trading Obat","productcategory":"Hasil Wakaf"},
            {"productid":"1291","productname":"Hasil Wakaf-Trading Pasar Baru","productcategory":"Hasil Wakaf"},
            {"productid":"1292","productname":"Hasil Wakaf-Training Center 99","productcategory":"Hasil Wakaf"},
            {"productid":"1293","productname":"Infak-Akikah","productcategory":"Infak"},
            {"productid":"1294","productname":"Infak-Alat Kesehatan RBC","productcategory":"Infak"},
            {"productid":"1295","productname":"Infak-Al-Hikmah","productcategory":"Infak"},
            {"productid":"1296","productname":"Infak-Barang","productcategory":"Infak"},
            {"productid":"1297","productname":"Infak-Beasiswa Pegiat Dakwah","productcategory":"Infak"},
            {"productid":"1298","productname":"Infak-Beasiswa Pemimpin Bangsa","productcategory":"Infak"},
            {"productid":"1299","productname":"Infak-Berbagi Bingkisan Bergizi","productcategory":"Infak"},
            {"productid":"1300","productname":"Infak-Berbagi Buka Shaum","productcategory":"Infak"},
            {"productid":"1301","productname":"Infak-Berbagi Kado Lebaran","productcategory":"Infak"},
            {"productid":"1302","productname":"Infak-Berbagi Perlengkapan Sekolah","productcategory":"Infak"},
            {"productid":"1303","productname":"Infak-Berbagi Sahur","productcategory":"Infak"},
            {"productid":"1304","productname":"Infak-Berbagi THR untuk Pedagang","productcategory":"Infak"},
            {"productid":"1305","productname":"Infak-Daily Sedekah","productcategory":"Infak"},
            {"productid":"1306","productname":"Infak-Dana Pengelola","productcategory":"Infak"},
            {"productid":"1307","productname":"Infak-Event","productcategory":"Infak"},
            {"productid":"1308","productname":"Infak-Fidyah","productcategory":"Infak"},
            {"productid":"1309","productname":"Ibunda","productcategory":"Infak"},
            {"productid":"1310","productname":"Infak-Kambing\/Domba Produktif","productcategory":"Infak"},
            {"productid":"1311","productname":"Infak-Kencleng","productcategory":"Infak"},
            {"productid":"1312","productname":"Infak-khusus","productcategory":"Infak"},
            {"productid":"1313","productname":"Infak-Khusus Yatim & Dhuafa","productcategory":"Infak"},
            {"productid":"1314","productname":"Infak-Lumbung Desa","productcategory":"Infak"},
            {"productid":"1315","productname":"Infak-Media Sosialisasi Wakaf","productcategory":"Wakaf"},
            {"productid":"1316","productname":"Infak-Mobil LKC","productcategory":"Infak"},
            {"productid":"1317","productname":"Infak-Operasioanl Distribusi Kurban","productcategory":"Infak"},
            {"productid":"1318","productname":"Infak-Paket Lebaran Yatim Dhuafa","productcategory":"Infak"},
            {"productid":"1319","productname":"Infak-Parcel Lebaran Rohinya","productcategory":"Infak"},
            {"productid":"1320","productname":"Infak-Pembangunan Happy Centre","productcategory":"Infak"},
            {"productid":"1321","productname":"Infak-Pembangunan Masjid Rohingya","productcategory":"Infak"},
            {"productid":"1322","productname":"Infak-Pendidikan","productcategory":"Infak"},
            {"productid":"1323","productname":"Infak-Pengajian","productcategory":"Infak"},
            {"productid":"1324","productname":"Infak-Pohon Produktif","productcategory":"Infak"},
            {"productid":"1325","productname":"Infak-Praktis","productcategory":"Infak"},
            {"productid":"1326","productname":"Infak-Profesi","productcategory":"Infak"},
            {"productid":"1327","productname":"Infak-Ramadhan","productcategory":"Infak"},
            {"productid":"1328","productname":"Infak-RBC","productcategory":"Infak"},
            {"productid":"1329","productname":"Infak-Rikaz","productcategory":"Infak"},
            {"productid":"1330","productname":"Infak-Sebar Nilai","productcategory":"Infak"},
            {"productid":"1331","productname":"Infak-Sedekah Inspirasi","productcategory":"Infak"},
            {"productid":"1332","productname":"Sedekah Makan","productcategory":"Dana Kemanusiaan"},
            {"productid":"1333","productname":"Infak-Sekolah Untuk Semua","productcategory":"Infak"},
            {"productid":"1334","productname":"Infak-Sembako Yatim&Dhuafa","productcategory":"Infak"},
            {"productid":"1335","productname":"Infak-Tajil,buka&sahur Rohingnya","productcategory":"Infak"},
            {"productid":"1336","productname":"Infak-THR Petani Dhuafa","productcategory":"Infak"},
            {"productid":"1337","productname":"Infak-Traktor Desa Ramadhan","productcategory":"Infak"},
            {"productid":"1339","productname":"Infak-Voucher","productcategory":"Infak"},
            {"productid":"1340","productname":"Infak-Tunai","productcategory":"Infak"},
            {"productid":"1341","productname":"Infak THK-Voucher","productcategory":"Infak THK"},
            {"productid":"1342","productname":"Sebar Nilai-Buku","productcategory":"Sebar Nilai"},
            {"productid":"1343","productname":"Sebar Nilai-Elektronik","productcategory":"Sebar Nilai"},
            {"productid":"1344","productname":"Sebar Nilai-Furniture","productcategory":"Sebar Nilai"},
            {"productid":"1345","productname":"Sebar Nilai-Kendaraan","productcategory":"Sebar Nilai"},
            {"productid":"1346","productname":"Sebar Nilai-Lain-lain","productcategory":"Sebar Nilai"},
            {"productid":"1347","productname":"Sebar Nilai-Pakaian","productcategory":"Sebar Nilai"},
            {"productid":"1348","productname":"Sebar Nilai-Perhiasan","productcategory":"Sebar Nilai"},
            {"productid":"1349","productname":"Sponsorship-Barang","productcategory":"Sponsorship"},
            {"productid":"1350","productname":"Sponsorship-Donasi","productcategory":"Sponsorship"},
            {"productid":"1351","productname":"Sponsorship-Hijaukan Ibadah","productcategory":"Sponsorship"},
            {"productid":"1352","productname":"Tabungan Kurban-10 Bulan","productcategory":"Tabungan Kurban"},
            {"productid":"1353","productname":"Tabungan Kurban-6 Bulan","productcategory":"Tabungan Kurban"},
            {"productid":"1354","productname":"Tabungan Kurban-Gabung Sapi","productcategory":"Tabungan Kurban"},
            {"productid":"1355","productname":"Tabungan Kurban-Kambing Tipe A","productcategory":"Tabungan Kurban"},
            {"productid":"1356","productname":"Tabungan Kurban-Kambing Tipe B","productcategory":"Tabungan Kurban"},
            {"productid":"1357","productname":"Tabungan Kurban-Sapi","productcategory":"Tabungan Kurban"},
            {"productid":"1358","productname":"Tebar Hewan Kurban-Infak THK","productcategory":"Infak"},
            {"productid":"1359","productname":"Tebar Hewan Kurban-K. Besar","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1360","productname":"Tebar Hewan Kurban-Kambing (Mengijinkan Gabung Sapi)","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1361","productname":"Tebar Hewan Kurban-Kambing (Tidak Mengijinkan Gabung Sapi)","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1362","productname":"Tebar Hewan Kurban-Kambing 1234","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1363","productname":"Tebar Hewan Kurban-Kambing 1250","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1364","productname":"Tebar Hewan Kurban-Kambing 1550","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1365","productname":"Tebar Hewan Kurban-Kambing 1775","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1366","productname":"Tebar Hewan Kurban-Kambing 2250","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1367","productname":"Tebar Hewan Kurban-Kambing 999","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1368","productname":"Tebar Hewan Kurban-Sapi","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1369","productname":"Tebar Hewan Kurban-Sapi (Gabungan 7 Pekurban)","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1370","productname":"Tebar Hewan Kurban-Tunai","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1371","productname":"Tebar Hewan Kurban-Voucher Kurban","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1372","productname":"Wakaf-Alat Kesehatan RBC","productcategory":"Wakaf"},
            {"productid":"1373","productname":"Wakaf-Alquran","productcategory":"Wakaf"},
            {"productid":"1374","productname":"Wakaf-Bahan Bangunan RBC","productcategory":"Wakaf"},
            {"productid":"1375","productname":"Wakaf-Barang","productcategory":"Wakaf"},
            {"productid":"1376","productname":"Wakaf-gedung 99","productcategory":"Wakaf"},
            {"productid":"1377","productname":"Wakaf-Infak Sebar Nilai","productcategory":"Wakaf"},
            {"productid":"1378","productname":"Wakaf-Infak Sewa Ruangan","productcategory":"Wakaf"},
            {"productid":"1379","productname":"Wakaf-Infak Wakaf Produktif","productcategory":"Wakaf"},
            {"productid":"1380","productname":"Wakaf-Kuttab Al-Fatih","productcategory":"Wakaf"},
            {"productid":"1381","productname":"Wakaf-Masjid Yahya Idrus","productcategory":"Wakaf"},
            {"productid":"1382","productname":"Wakaf-Masjid & Pesantren Al Quran","productcategory":"Wakaf"},
            {"productid":"1383","productname":"Wakaf-Pemakaman ( Tabungan )","productcategory":"Wakaf"},
            {"productid":"1384","productname":"Wakaf-Pemakaman Muslim","productcategory":"Wakaf"},
            {"productid":"1385","productname":"Wakaf-Penyediaan Lahan Pemakaman Dhuafa","productcategory":"Wakaf"},
            {"productid":"1386","productname":"Wakaf-Pohon Produktif","productcategory":"Wakaf"},
            {"productid":"1387","productname":"Wakaf-Produktif","productcategory":"Wakaf"},
            {"productid":"1388","productname":"Wakaf-Produktif (Tabungan)","productcategory":"Wakaf"},
            {"productid":"1389","productname":"Wakaf-KWIA","productcategory":"Wakaf"},
            {"productid":"1390","productname":"Wakaf-Rumah Makan","productcategory":"Wakaf"},
            {"productid":"1391","productname":"Wakaf-Sawah Produktif","productcategory":"Wakaf"},
            {"productid":"1392","productname":"Wakaf-Tunai","productcategory":"Wakaf"},
            {"productid":"1393","productname":"Wakaf-Tunai Mesjid FMP","productcategory":"Wakaf"},
            {"productid":"1394","productname":"Wakaf-Voucher","productcategory":"Wakaf"},
            {"productid":"1395","productname":"Wakaf Pengembalian Investasi-Apotek Ebah Farma","productcategory":"Wakaf Pengembalian Investasi"},
            {"productid":"1396","productname":"Wakaf Pengembalian Investasi-Lain-Lain","productcategory":"Wakaf Pengembalian Investasi"},
            {"productid":"1397","productname":"Wakaf Pengembalian Investasi-Ozil Kebab","productcategory":"Wakaf"},
            {"productid":"1398","productname":"Wakaf Pengembalian Investasi-PGS 1","productcategory":"Wakaf Pengembalian Investasi"},
            {"productid":"1399","productname":"Wakaf Pengembalian Investasi-PGS 2","productcategory":"Wakaf Pengembalian Investasi"},
            {"productid":"1400","productname":"Wakaf Pengembalian Investasi-RM Ampera Pasteur","productcategory":"Wakaf Pengembalian Investasi"},
            {"productid":"1401","productname":"Wakaf Pengembalian Investasi-Toko Moorish","productcategory":"Wakaf Pengembalian Investasi"},
            {"productid":"1402","productname":"Wakaf Pengembalian Investasi-Toko Vamosh","productcategory":"Wakaf Pengembalian Investasi"},
            {"productid":"1403","productname":"Zakat-Emas & Perak","productcategory":"Zakat"},
            {"productid":"1404","productname":"Zakat-Entitas","productcategory":"Zakat"},
            {"productid":"1405","productname":"Zakat-Fitrah","productcategory":"Zakat"},
            {"productid":"1406","productname":"Zakat-Maal","productcategory":"Zakat"},
            {"productid":"1407","productname":"Zakat-Penghasilan","productcategory":"Zakat"},
            {"productid":"1408","productname":"Zakat-Perdagangan","productcategory":"Zakat"},
            {"productid":"1409","productname":"Zakat-Pertanian","productcategory":"Zakat"},
            {"productid":"1410","productname":"Zakat-Rikaz","productcategory":"Zakat"},
            {"productid":"28301","productname":"-DUMMY Program Donasi 1","productcategory":""},
            {"productid":"28315","productname":"Wakaf-Kawasan Wakaf Terpadu Daarul Aulia","productcategory":"Wakaf"},
            {"productid":"578522","productname":"Dana Kemanusiaan-Tsunami Selat Sunda","productcategory":"Dana Kemanusiaan"},
            {"productid":"578537","productname":"Dana Kemanusiaan-Longsor Sukabumi","productcategory":"Dana Kemanusiaan"},
            {"productid":"579396","productname":"Dana Kemanusiaan-Bencana Tasikmalaya","productcategory":"Dana Kemanusiaan"},
            {"productid":"642458","productname":"Infak-IRC","productcategory":"Infak"},
            {"productid":"642459","productname":"Wakaf-IRC","productcategory":"Wakaf"},
            {"productid":"711069","productname":"Wakaf-Tanah","productcategory":"Wakaf"},
            {"productid":"711653","productname":"Dana Kemanusiaan-Banjir Sentani","productcategory":"Dana Kemanusiaan"},
            {"productid":"816901","productname":"Tebar Hewan Kurban-Kambing 1111","productcategory":"Tebar Hewan Kurban"},
            {"productid":"816928","productname":"Tebar Hewan Kurban-Kambing 1432","productcategory":"Tebar Hewan Kurban"},
            {"productid":"1026685","productname":"Infak-Berbagi Al-Quran (Rohingya)","productcategory":"Infak"},
            {"productid":"1026686","productname":"Infak-Berbagi Buka Shaum (Palestina)","productcategory":"Infak"},
            {"productid":"1026687","productname":"Infak-Berbagi Buka Shaum (Rohingnya)","productcategory":"Infak"},
            {"productid":"1026688","productname":"Infak-Berbagi Kado Lebaran (Palestina)","productcategory":"Infak"},
            {"productid":"1026689","productname":"Green Kurban-Domba Gaza","productcategory":"Green Kurban"},
            {"productid":"1026690","productname":"Green Kurban-Green Kurban-Sapi Gaza","productcategory":"Green Kurban"},
            {"productid":"1026691","productname":"Green Kurban-Sapi Rohingya","productcategory":"Green Kurban"},
            {"productid":"1026692","productname":"Infak-Berbagi Buka Shaum (Suriah)","productcategory":"Infak"},
            {"productid":"1026693","productname":"Wakaf-Integrity Farm","productcategory":"Wakaf"},
            {"productid":"1026694","productname":"Wakaf-Klinik Ibu & Anak","productcategory":"Wakaf"},
            {"productid":"1026695","productname":"Wakaf-Sajadah Kuttab","productcategory":"Wakaf"},
            {"productid":"1026696","productname":"Wakaf-Sumur Kuttab Al-Fatih","productcategory":"Wakaf"},
            {"productid":"1026697","productname":"Wakaf-Peternakan","productcategory":"Wakaf"},
            {"productid":"1041967","productname":"Dana Kemanusiaan-Papua","productcategory":"Dana Kemanusiaan"},
            {"productid":"1041968","productname":"Dana Kemanusiaan-Riau","productcategory":"Dana Kemanusiaan"},
            {"productid":"1053144","productname":"Wakaf-9 In 1","productcategory":"Wakaf"},
            {"productid":"1053942","productname":"Wakaf-Sumur","productcategory":"Wakaf"},
            {"productid":"1053946","productname":"Dana Kemanusiaan-Bencana Banjir","productcategory":"Dana Kemanusiaan"},
            {"productid":"1055382","productname":"Wakaf-9 in 1 (Tabungan)","productcategory":"Wakaf"},
            {"productid":"1056636","productname":"Zakat","productcategory":"Zakat"},
            {"productid":"1060382","productname":"Dana Kemanusiaan - #Sinergilawancovid","productcategory":"Dana Kemanusiaan"},
            {"productid":"1069952","productname":"Dana Kemanusiaan-Bantu Petani dan Mahasiswa Terdampak Corona","productcategory":"Dana Kemanusiaan"},
            {"productid":"1077456","productname":"Dana Kemanusiaan-Banjir Masamba","productcategory":"Dana Kemanusiaan"},
            {"productid":"1077614","productname":"Green Kurban-Kambing Special Offer","productcategory":"Green Kurban"},
            {"productid":"1081857","productname":"Dana Kemanusiaan-Banjir Sukabumi","productcategory":"Dana Kemanusiaan"},
            {"productid":"1087134","productname":"Wakaf-Qard","productcategory":"Wakaf"},
            {"productid":"1087135","productname":"Wakaf-Sumber Air","productcategory":"Wakaf"},
            {"productid":"1091382","productname":"Infak-Kemanusiaan","productcategory":"Infak"},
            {"productid":"1091383","productname":"Infak-Sedekah Umum","productcategory":"Infak"},
            {"productid":"1091386","productname":"Dana Kemanusiaan-Longsor","productcategory":"Dana Kemanusiaan"},
            {"productid":"1091387","productname":"Dana Kemanusiaan-Banjir","productcategory":"Dana Kemanusiaan"},
            {"productid":"1099339","productname":"Infak-Palestina","productcategory":"Infak"},
            {"productid":"1100624","productname":"Infak-Media Sosialisasi Wakaf 9 in 1","productcategory":"Wakaf"},
            {"productid":"1101664","productname":"Green Kurban-Mandiri Sapi","productcategory":"Green Kurban"},
            {"productid":"1101665","productname":"Green Kurban-Mandiri Kambing","productcategory":"Green Kurban"},
            {"productid":"1104459","productname":"Green Kurban-Hewan Hidup","productcategory":"Green Kurban"},
            {"productid":"1116964","productname":"Dana Kemanusiaan-Jembatan","productcategory":"Dana Kemanusiaan"},
            {"productid":"1119809","productname":"Wakaf-9 in 1 Bogor (Tabungan)","productcategory":"Wakaf"},
            {"productid":"1119810","productname":"Wakaf-9 in1 Bogor","productcategory":"Wakaf"},
            {"productid":"1119956","productname":"Infak-Berbagi Kado Yatim, Dhuafa dan Difabel","productcategory":"Infak"},
            {"productid":"1119957","productname":"Infak-Berbagi Kado Yatim, Dhuafa dan Difabel (Palestina)","productcategory":"Infak"},
            {"productid":"1119958","productname":"Infak-Al-Quran","productcategory":"Infak"},
            {"productid":"1120490","productname":"Dana Non Halal","productcategory":"Dana Non Halal"},
            {"productid":"1121750","productname":"Infak-Gerakan Sedekah Air","productcategory":"Infak"},
            {"productid":"1121752","productname":"Wakaf-Green Wakaf","productcategory":"Wakaf"},
            {"productid":"1126204","productname":"Infak-Pesantren Mulia","productcategory":"Infak"},
            {"productid":"1128781","productname":"Green Kurban-Kurban Terbaik (Domba)","productcategory":"Green Kurban"},
            {"productid":"1128783","productname":"Green Kurban-Kurban Terjangkau (Domba)","productcategory":"Green Kurban"},
            {"productid":"1128795","productname":"Tabungan Kurban-Kurban Terbaik","productcategory":"Tabungan Kurban"},
            {"productid":"1128796","productname":"Tabungan Kurban-Kurban Terjangkau","productcategory":"Tabungan Kurban"},
            {"productid":"1129436","productname":"Hasil Wakaf-Anggrek","productcategory":"Hasil Wakaf"},
            {"productid":"1129811","productname":"Green Kurban Mandiri-KAMBING","productcategory":"Green Kurban Mandiri"},
            {"productid":"1129812","productname":"Green Kurban Mandiri-SAPI","productcategory":"Green Kurban Mandiri"},
            {"productid":"1130487","productname":"Kurban WIF-Sapi","productcategory":"Kurban WIF"},
            {"productid":"1130488","productname":"Kurban WIF-Domba","productcategory":"Kurban WIF"},
            {"productid":"1131042","productname":"Green Kurban-Sapi Afrika","productcategory":"Green Kurban"},
            {"productid":"1131043","productname":"Green Kurban-Domba Afrika","productcategory":"Green Kurban"},
            {"productid":"1134993","productname":"Infak-Media Sosialisasi Wakaf MDA","productcategory":"Wakaf"},
            {"productid":"1142271","productname":"Infak-Kuttab Al-Fatih","productcategory":"Infak"},
            {"productid":"1142387","productname":"Wakaf-9 in 1 - Cikalongwetan","productcategory":"Wakaf"},
            {"productid":"1142388","productname":"Wakaf-9 in 1 - Cikalongwetan (Tabungan)","productcategory":"Wakaf"},
            {"productid":"1142389","productname":"Infak-Media Sosialisasi 9 in 1 Cikalongwetan","productcategory":"Wakaf"},
            {"productid":"1142395","productname":"Infak-Kuttab Al-Fatih","productcategory":"Infak"},
            {"productid":"1144694","productname":"Wakaf-Ambulance","productcategory":"Wakaf"},
            {"productid":"1148549","productname":"Non-ZIS-Non-ZIS","productcategory":"non-zis"},
            {"productid":"1149233","productname":"Wakaf-Wakaf Uang","productcategory":"Wakaf"},
            {"productid":"1152460","productname":"Infak-Berbagi Bingkisan Guru","productcategory":"Infak"},
            {"productid":"1152461","productname":"Infak-Berbagi Tiket Mudik","productcategory":"Infak"},
            {"productid":"1153106","productname":"Infak-Operational Amil","productcategory":"Infak"},
            {"productid":"1153790","productname":"Infak-Dana Titipan","productcategory":"Infak"},
            {"productid":"1158902","productname":"Zakat-Perusahaan","productcategory":"Zakat"},
            {"productid":"1160322","productname":"Green Kurban-Sapi Rohingya B","productcategory":"Green Kurban"},
            {"productid":"1165301","productname":"Sinergi Tanggap Bencana-Sinergi Tanggap Bencana","productcategory":""},
            {"productid":"1165303","productname":"-Sinergi Tanggap Bencana","productcategory":""},
            {"productid":"1165305","productname":"-Sinergi Tanggap Bencana","productcategory":""},
            {"productid":"1165310","productname":"Dana Kemanusiaan-Sinergi Tanggap Bencana","productcategory":"Dana Kemanusiaan"},
            {"productid":"1166886","productname":"Akikah-Akikah","productcategory":"Akikah"},
            {"productid":"1167092","productname":"Infak-Operasional Nazir","productcategory":"Wakaf"}
        ]';

        $programData = json_decode($datas, true);
        $categoryIds = [];

        $categoryNames = array_column($programData, 'productcategory');
        $categoryResults = ProgramCategory::whereIn('category_name', $categoryNames)->get();
        
        foreach ($categoryResults as $categoryResult) {
            $categoryIds[$categoryResult->category_name] = $categoryResult->id;
        }

            $insertData = [];

        foreach ($programData as $data) {
            $categoryId = $categoryIds[$data['productcategory']] ?? null;
        
            if ($categoryId !== null) {
                $program = new Program([
                    'ulid' => Ulid::generate(),
                    'id' => $data['productid'],
                    'program_name' => $data['productname'],
                    'program_category_id' => $categoryId,
                ]);
        
                $program->save();
            }
        }
        
        
        
    }
}
